/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://6ssdjhnnvvfztdchumble4hdr4.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xbp3nqtzlngvfm75rpbddicsay",
    "aws_cognito_identity_pool_id": "eu-north-1:1383e4fb-6f2d-462e-bc3d-7b9adc03e8d1",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_BtdPc9wwd",
    "aws_user_pools_web_client_id": "7ic7rms8513dj14vdbdlqtig7d",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "GIVEN_NAME",
        "FAMILY_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "balticshortsstack-source71e471f1-aacfeq17yzau",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
